### ISSUE TITLE
Emulate Spot Instance ITN events

### ISSUE THREAD

**Issue by eldondevat** [aws/aws-node-termination-handler#110]
It would be nice to be able to emulate the sorts of events this daemonset reacts to. We are interested in doing more testing around implementing this daemonset, and how it would interact with our application, but I don't see an obvious path forward from a test perspective. 

Node replacement on our spot pool is relatively infrequent. I would be open to sending a PR if the team has interest. My initial thought was a signal handler (SIGQUIT, SIGHUP, SIGUSR1/2, etc). If that's too out-of-left-field, maybe webhook or webhook response?
Thanks!

**Comment by mattrandallbecker** [comment]
I completely agree.  Customers want to be resilient to Spot interruptions but it is difficult to test how your code/environment responds if you end up not seeing an interruption for extended periods of time.

In our integration tests we developed a [metadata proxy](https://github.com/aws/aws-node-termination-handler/tree/master/config/helm/ec2-metadata-test-proxy) that we use to spoof an ITN so that we can test our code behaves as expected.  That being said I don't think the proxy in its current state is particularly consumable by others to include in their test harnesses and so we planned on releasing a separate project that is a configurable interruption mocking project.

Does that sound like it would be useful to you and meet your needs?

**Comment by eldondevat** [comment]
That sounds like it would be useful for sure. It sounds more involved than what I was thinking. I am also not sure how the mocking element would work with other metadata-adjacent services (kiam for example). We were not specifically planning on writing this as a test harness, but simply using it to schedule these kinds of events on a more continual basis in our development/nonprod clusters.

**Comment by dchelupati** [comment]
Thanks for feedback. We are also looking at providing interruption emulator API that allows you to mock Spot 2 minute ITNs for the running Spot Instances and eventually terminate them. Do you think this would be useful for your testing? Also, can you share what does your code do upon receiving a 2 minute ITN?

**Comment by bwagner5** [comment]
@eldondevat It would be possible to run the mock metadata proxy in a reverse proxy mode so that the adjacent metadata paths are accessible as normal. 

something like this should work:

```
# This is the setup that https://github.com/stefansundin/ec2-metadata-filter runs in 
sudo adduser --system --no-create-home --home /nonexistent ec2-metadata
sudo iptables -t nat -A OUTPUT -d 169.254.169.254 -p tcp -m owner \! --uid-owner ec2-metadata -j REDIRECT --to-port 16925
```

The metadata mock would be listening on the 16925 port as the ec2-metadata user and would intercept the configured paths and then reverse proxy all the rest to the actual metadata service. A mode could then be added to metadata mock to schedule random (or cron style) events on any of the paths. 

Does this seem plausible for the type of testing you are thinking of?

**Comment by leoskyrocker** [comment]
I think the above approach will be feasible for our use case too. Btw, could you suggest a way we could simulate this (either from the AWS console or anyhow) for now?

**Comment by ruecarlo** [comment]
@leoskyrocker at the moment the only way to trigger the notification from interruption through the console is by using EC2 Fleet in maintain mode or Spot Fleet, procure some spot instances, and then decrease the target capacity of the fleet. There is a [step by step guide](https://ec2spotworkshops.com/ec2_spot_fleet_web_app/interruption_testing.html) in the http://ec2spotworkshops.com site. Hope that helps; Still the intention of this thread is how we can help to automate integration tests nicely in all scenarios.

**Comment by leoskyrocker** [comment]
Is there a way to do it for ASGs? We’re not using spot fleet and seems like the Capacity setting is also disabled.

**Comment by ruecarlo** [comment]
Not with ASG's at the moment. Thus @dchelupati's point on gathering feedback on an emulator API. If you can provide any feedback in that direction, it will be great for us to understand use cases and scenarios.

**Comment by leoskyrocker** [comment]
We use SI to process background jobs, and on ITN we would put the currently running he back to the queue so that next worker process can pick it up again. Without their termination notice triggering a drain, we would end up with jobs that are in a corrupted state. Therefore, we cannot use this handler and SI before we have a way to test this. Please suggest way I can help to speed this up so we can use SI ASAP. Thanks!

**Comment by leoskyrocker** [comment]
I re-read OPs question and I think he’s also just trying to verify that this tool works in general instead of expecting to run integration tests for this?

So I had two options in mind:
1) manually bring up a spot fleet and force my fleet instances to join the Kops cluster
2) build an API server that mocks the metadata service which returns an ITN.

For 1) I am not able to make the instance join the existing Kops cluster, so I’m falling back to 2), but would appreciate if your team can provide a bare minimum information of what endpoints will be needed and the minimum response shape it would expect. I’m assuming it doesn’t consume the whole metadata service, and it’d be a bit time consuming to go through everything to figure that out so would really appreciate if someone already has that info handy.

**Comment by ruecarlo** [comment]
Just in case others have to reproduce; Using the bootstrap (i.e: checking the LaunchTemplate details) of already existing ASG/nodegroups is the right starting point.

**Comment by leoskyrocker** [comment]
Yas!!! Tho very important one note:

Tag your ec2 instance with KubernetesCluster just like any other worker nodes.

That’s the only thing we were missing and I thought the world is ending.

**Comment by bwagner5** [comment]
@leoskyrocker Glad to hear you were able to test. Just an FYI on your option 2: We created a small mock ec2-metadata server for use in our integration tests that you can run **standalone** here: https://github.com/aws/aws-node-termination-handler/tree/master/test/ec2-metadata-test-proxy. It will mock out the metadata necessary to run the aws-node-termination-handler:
 - /latest/meta-data/spot/instance-action
 - /latest/meta-data/events/maintenance/scheduled
 - /latest/meta-data/instance-id
 - /latest/meta-data/instance-type
 - /latest/meta-data/public-hostname
 - /latest/meta-data/public-ipv4
 - /latest/meta-data/local-hostname
 - /latest/meta-data/local-ipv

The above was only meant to be used for integration tests, but we're working on a more consumable version that will live in a separate repo and will be more user friendly.

**Comment by ari-becker** [comment]
We've run into this issue.

The ideal solution, from our point of view, is not a mock metadata proxy but rather the real thing. We'd rather have access to an AWS API which allowed us to provoke a real event for a real EC2 instance.

Not sure if anyone here has the ear of the relevant person inside AWS to make this happen, but it's worth enough of a shot to write about it here.

**Comment by dchelupati** [comment]
@ari-becker  Thanks for your request. We are looking to provide an API that does exactly that.

**Comment by andredurao** [comment]
I've managed to test it running the mock server also, just some comments I would love to know beforehand:

* Change the value of the const `instanceID`
* set the PORT env value first, `PORT=16925 ./ec2-metadata-test-proxy`
* remove the forward iptables rule to restore metadata

**Comment by bwagner5** [comment]
@andredurao 

InstanceID and other attributes of the mock not being configurable are definitely one of the deficiencies of the mock in this repo. We are working on open sourcing a more consumable ec2 metadata mock as its own project that will allow for much greater flexibility with configuration options.  The release for that should be soon, within the next few months. I'll post on this issue when we do release that separate project. 

 - Port 16925 was just an example copied from the other repo's similar setup of mocking out EC2 Metadata. But yes, if you were to use those iptable rules, you'd need to set the port like you've done. 
 - Yes, you'd have to remove the iptables rule to restore the original metadata. Rebooting the instance would also remove the iptables rules since, by default, they will not persist.

**Comment by buckyguy33** [comment]
I used this project to simulate a working EC2 metadata spot termination endpoint response.
https://github.com/Shogan/ec2-spot-termination-simulator

**Comment by rajakshay** [comment]
> I used this project to simulate a working EC2 metadata spot termination endpoint response.
> https://github.com/Shogan/ec2-spot-termination-simulator

I can't seem to be able to get the simulator to work, and have opened an issue with here: https://github.com/Shogan/ec2-spot-termination-simulator/issues/1

**Comment by rajakshay** [comment]
Is there any easy way I could simulate a spotInstance termination so that I could test the termination-handler, and how my applications respond to the drain.

**Comment by jillmon** [comment]
Currently the only way to test for spot terminations is to scale down your spot fleet using the AWS console or CLI.

We are currently working on a project called Amazon EC2 Metadata Mock. It has a planned v0.9.0 release set for the end of the week. This project was build with the purpose of simulating Amazon EC2 instance metadata for local testing, and should be a step towards addressing your need.

**Comment by rajakshay** [comment]
> Currently the only way to test for spot terminations is to scale down your spot fleet using the AWS console or CLI.

We use mixedInstance ASG on KOPS. Unfortunately, it does not allow me to test it that. way. Looking forward to the _Amazon EC2 Metadata Mock_ release. Cheers!!

**Comment by leoskyrocker** [comment]
> > Currently the only way to test for spot terminations is to scale down your spot fleet using the AWS console or CLI.
> 
> We use mixedInstance ASG on KOPS. Unfortunately, it does not allow me to test it that. way. Looking forward to the _Amazon EC2 Metadata Mock_ release. Thank you.

If you really really need to do this, use this steps here: https://github.com/aws/aws-node-termination-handler/issues/110#issuecomment-601491179

**Comment by jillmon** [comment]
The Metadata Mock repository is now public. It can be found here: https://github.com/aws/amazon-ec2-metadata-mock. While 90% of the development is complete, there are still some changes in flight. This is the v0.9 release. v1 will be released once the remaining development work is complete.

**Comment by bwagner5** [comment]
v1.0.0 of the amazon-ec2-metadata-mock was released https://github.com/aws/amazon-ec2-metadata-mock/releases/tag/v1.0.0
