### ISSUE TITLE
Expand to include non-spot instances

### ISSUE THREAD

**Issue by aaronmell** [aws/aws-node-termination-handler#14]
We currently use a lambda to drain our instances, would prefer to use this.

**Comment by aaronmell** [comment]
See https://github.com/aws/containers-roadmap/issues/430

**Comment by mattrandallbecker** [comment]
Ah yes, thanks for the reference, we are actually aware of that feature request and are hoping to expand this termination handler in the future to do exactly that.  That is why we named it aws-node-termination-handler rather than aws-spot-node-termination-handler.

**Comment by rtripat** [comment]
If you are using EKS, then [EKS Managed node group](https://docs.aws.amazon.com/en_us/eks/latest/userguide/managed-node-groups.html) performs a drain when AutoScalingGroup terminates an instance on scale-in or [rebalancing](https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-benefits.html). Does that satisfy the requirements?

**Comment by aaronmell** [comment]
@rtripat It would if it allowed using a custom AMI built on top of the standard AMI.

**Comment by bwagner5** [comment]
We want to take a more generic kubernetes approach to this problem and not rely on a specific service offering. A lot of users are provisioning with kops, cloudformation, terraform, or some hybrid so we're working on a solution that will be plug-and-play for all of those different methods.

**Comment by barryib** [comment]
@bwagner5 We actually use lambda and SQS queue to handle node termination. We'll love to use this instead.

How can community help on this ? Is there any design or plan ? 

- ASG lifecycle hooks + Cloudwatch events ?
- ASG lifecycle hooks + SQS ?
- Something else ?

**Comment by bwagner5** [comment]
Hey @barryib !  

As mentioned above, we'd like to take an approach that does not require any sort of out-of-band setup, controllers managing AWS resources, or credentials in general. This allows us to support the vast majority of kubernetes setups. 

My proposed implementation to accomplish this is to use the acpid socket to catch power button events.  When a power button event is received by aws-node-termination-handler, it will trigger a node cordon. The operating system will continue processing the ACPI event like normal by sending SIGTERM to init and the init system propagating the SIGTERM to its managed processes, one of which should be the kubelet. The kubelet will start propagating the SIGTERM to pods and containers managed by it. Pods will have to catch sigterm and perform proper application specific shutdown procedures and are given the configurable kubernetes pod termination grace period before a SIGKILL is sent to the containers. The OS should wait on kubelet to exit and then proceed with the shutdown.  

I have some more testing and verification of these assumptions to perform, but any feedback and discussion is welcome!  I'll post my test results here when they have concluded.

**Comment by barryib** [comment]
@bwagner5 Sounds interesting and eager to see your tests results. I think this will probably work for draining, but there we are still missing the node coordination during shutdown.

As you said, people use kops, cloudformation and terraform to provision their cluster. And so far, only cloudformation can handle rolling upgrade. How can we achieve this in terraform by exemple ? Because sending SIGTERM to every nodes will lead to an outage => all nodes will try to drain at same time. How can we coordinate them ?

**Comment by bwagner5** [comment]
I don't think the coordination of node draining belongs in this specific tool.  Coordinating infrastructure deployments will vary drastically depending on deployment strategies (blue/green vs rolling vs in-place patching, etc.). The node-termination-handler could be utilized to perform the drain in each of these cases, but it would be the responsibility of your specific deployment tool to maintain a certain number of nodes to run your pods.  I think this tool should stay fairly light weight and focused on cordon/draining with very few dependencies.

**Comment by jaypipes** [comment]
Yeah, I agree with @bwagner5 here regarding the separation of concerns. Tools in a layer above the NTH should decide how to handle rolling node upgrade procedures.

**Comment by spolspol** [comment]
There are circumstance where otherwise 'separate' termination events are coupled by common cause.

Like in my use case (see link) where major portion of ASG managed SPOTs is terminated
and replaced in a short space of time they often come unbalanced across AZs. ASG rebalancing event soon follows and is not handled gracefully.

Looking at 4 months worth of data since we started using this setup - rebalancing follows SPOT terminations in at least 80% of SPOT termination cases.

https://github.com/aws/aws-node-termination-handler/issues/95

**Comment by bwagner5** [comment]
@spolspol sounds like the planned functionality of draining on any instance shutdown would handle the out-of-band rebalance events as well as any other events that are outside of normal shutdown events where prior notification is not given (i.e. operator terminates from console or API). We're hoping to get this functionality released soon!  Let me know if you think the solution we're pursuing is missing anything.

**Comment by spolspol** [comment]
@bwagner5 would you guys have any ETA on release for this feature?

**Comment by jillmon** [comment]
Hello, we're currently working on this feature and expect to be complete in a few weeks. We want to make sure that it is adequately stress tested internally before releasing to the public.

**Comment by mattrandallbecker** [comment]
Unfortunately, our testing revealed a critical weaknesses in our approach, and we were only able to make the feature function as intended on [newest EC2 platform instances](https://aws.amazon.com/ec2/nitro/).  Due to the feature not working on 3rd or 4th gen instances, we don't think it makes sense to release the feature as we've developed it.

As a result, we'll have to go back to the drawing board and investigate alternative mechanisms for comprehensive handling of EC2 shutdown events.  Our current best idea is to pivot the project from a daemonset to a controller which will require permissions to consume CloudWatch Events and ASG Lifecycle Hooks.  This will require some fundamental changes to the project; however, this may be the only way to handle things like AZ rebalance cleanly.

**Comment by lindsaygrace** [comment]
> Unfortunately, our testing revealed a critical weaknesses in our approach, and we were only able to make the feature function as intended on [newest EC2 platform instances](https://aws.amazon.com/ec2/nitro/). Due to the feature not working on 3rd or 4th gen instances, we don't think it makes sense to release the feature as we've developed it.
> 
> As a result, we'll have to go back to the drawing board and investigate alternative mechanisms for comprehensive handling of EC2 shutdown events. Our current best idea is to pivot the project from a daemonset to a controller which will require permissions to consume CloudWatch Events and ASG Lifecycle Hooks. This will require some fundamental changes to the project; however, this may be the only way to handle things like AZ rebalance cleanly.

I think a lot of people would be quite okay with that limitation if its enabled via a flag

**Comment by mattrandallbecker** [comment]
The limitation would cause a forking since the new method will require IAM permissions and we'd have to continue to support both or deprecate one forcing incompatibility.  Currently we would rather deliver a comprehensive solution, but it will take us some time to do so given some other commitments at the moment. Sorry for the delay.

**Comment by ffjia** [comment]
It'd nice if `aws-node-termination-handler` can, somehow, integrate with tools like [amazon-k8s-node-drainer](https://github.com/aws-samples/amazon-k8s-node-drainer). We could then have a unified solution to deal with instance termination issue gracefully.

**Comment by bwagner5** [comment]
Hey everyone! 👋  We have listened to your request to expand the aws-node-termination-handler to include all EC2 instances and not just Spot.  

We have pushed a branch to the repo [queue-processor]( https://github.com/aws/aws-node-termination-handler/tree/queue-processor) that allows aws-node-termination-handler to run as a deployment in your cluster and respond to EventBridge termination events from ASG, EC2, and Spot. 

Check out the new README on that branch and let us know what you think
https://github.com/aws/aws-node-termination-handler/tree/queue-processor

This new functionality is currently in Alpha, but we would love your feedback!

**Comment by bwagner5** [comment]
Assets have been created so that it's easier to test the new queue-processor functionality! https://github.com/aws/aws-node-termination-handler/releases/tag/v1.9.0

Post back here if you've tried it out!

**Comment by philomory** [comment]
@bwagner5 The new functionality is very nice, but it's a _lot_ more complex to set up than the prior method or the proposed solution based on `acpid`. Is there any chance for some more detailed guidance on how the setup of this works, beyond what's in the readme? For example, if I have multiple clusters, each with multiple worker groups, do I need an SQS queue per cluster? Per worker group? 

Selfishly, since we only use Nitro-capable instances in our clusters, I'd love it if the DaemonSet model added support for the `acpid` method, so that people with compatible instances could get the benefits without the additional complexity. But I do understand that maintaining multiple methods of accomplishing the same thing isn't a great plan on your end.
