### ISSUE TITLE
Error getting response from instance metadata

### ISSUE THREAD

**Issue by kivagant-ba** [aws/aws-node-termination-handler#21]
Hello.

I am trying to test node-termination-handler. It has been running for a couple of weeks and I didn't see anything in logs except two problems. One is described in https://github.com/aws/aws-node-termination-handler/issues/20, another error is:

```Error getting response from instance metadata  Get http://169.254.169.254/latest/meta-data/spot/instance-action: dial tcp 169.254.169.254:80: connect: connection refused```

After the error the handler died and was restarted. I cannot really understand if the tool works somehow or not. 🤔 Is the error critical or it is something temporary? Do I need to react on it?

I would appreciate any instructions how to use the handler and how its logs really must look like.

**Comment by dileep-p** [comment]
Same here +1

**Comment by mattrandallbecker** [comment]
Our prevailing theory is a transient network issue causes the connection to be refused at which point the error causes the daemonset pod to restart.  I can see in my personal cluster in about 45 days of running it has happened twice.

We'll make an update to attempt retries on connection issues to prevent the pod from restarting in this failure scenario.  We have integration tests and have tested the handler internally and it should be working as intended other than the periodic restarts due to transient networking issues.

**Comment by dileep-p** [comment]
We got around 3 restarts in 1 hour and then it becomes stable.

**Comment by mattrandallbecker** [comment]
Just to follow up on the thread, we've merged a PR that adds retries to the metadata polling, we hope that alleviates the fatals we were seeing before.

If you continue to see issues with the new image please let us know.
