### ISSUE TITLE
execute custom script during spot notification event

### ISSUE THREAD

**Issue by amrragab8080** [aws/aws-node-termination-handler#223]
Is it possible to specify a script I want to run when the spot termination notice is read from the instance metadata? The use case here is that in the 2 minute time window I want to transfer files generated in my pod back to S3. I think this will be useful in a machine learning context if I can transfer my checkpoints.

**Comment by haugenj** [comment]
Hey thanks for the question! At the moment this is not a supported feature of aws-node-termination-hander.

I vaguely remember discussing such a feature with @bwagner5 a while back and I can't remember where we landed on it. He'll be back in the office on Monday, I'll reconnect with him then get back to you.

**Comment by YakobovLior** [comment]
Hey @haugenj 
instead of performing custom script, is it possible to make the alert send some information based on Kubernetes labels?
For example, we have configured the Daemonset to work on specific node groups (with --set nodeSelector.lifecycle=<name>),
so we would like to have the ability to know from which node group the spot interrupt alert came.

Thanks,
Lior

**Comment by ruecarlo** [comment]
@amrragab8080; I'm guessing the question is how to trigger that notification for the script to be executed and within which scope it will run. 

By default the notification for termination is captured by the [aws node termination handler daemonset](https://github.com/aws/aws-node-termination-handler/blob/95fdc025df8f92b725f988869854917d961cc14b/cmd/node-termination-handler.go#L182) and handled/passed to the control plane in the form of a cordon + drain (configurable to cordon-only). By default when the drain signal is issued, you'll get a notification for a SIGTERM in the containers running your pods (and also by default but configurable a 30 second difference between the SIGTERM and final SIGKILL signal that kills up the process). 

At the moment is up to the developer of the application to capture the SIGTERM signal within the context of the container and run whichever code that is fit to do a graceful termination (including copying files to S3, etc).

**Comment by amrragab8080** [comment]
@ruecarlo,
It might be a more elegant solution if the daemonset launched a user specified sidecar container which handled the spot termination logic. Logical separation of the worker code and spot termination code would be better than trying to manage/monitor SIGTERM in the worker pod.

**Comment by ruecarlo** [comment]
@amrragab8080  Yup, that's what I mean in regards to defining well which is the scope the signal will be handled and within which scope it gets executed.

The spot termination logic will still require access to your Deep Learning weights, wherever those are; A sidecar might be a good solution to get there;

**Comment by amrragab8080** [comment]
@ruecarlo, Thank you for the quick response
> additionally, the sidecar still will get the SIGTERM signal that can be used and captured as a generic thing to run that script; Is that what you were thinking of ? (kind of an admission hook that will deploy a sidecar with the custom script and a wrapper that intercept SIGTERM and runs that script ? )

That correct, do you have an example of that?
In my case I have my weights stored on EFS, but could work with FSx, or EBS since I can pass my pvc into the sidecar.

**Comment by ruecarlo** [comment]
Nope, I don' have any example at the moment, unfortunately @amrragab8080. 

One of the things that was kind of preventing me so far from trying that is thinking about race conditions between the actual container and the sidecar. I've recommended so far to have the logic within the container to avoid potential race conditions on what finishes first and what is the state of the resources to free up/work with. Think about the SIGTERM within your tensorflow container dumping weights into EFS/ESx/Last Layer of the container in EBS and the side-car reading that file and uploading to S3 half-way when that happens, think how the logic to avoid this case breaks a bit the logical separation... 

In Kubernetes 1.19 there will be more control over the lifecycle of the pods (when they are initialised) and avoid this race conditions https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/0753-sidecarcontainers.md. Once that this come to place it will make sense to split up parts of the termination logic as you point out, and have a safe implementation.

**Comment by amrragab8080** [comment]
> Nope, I don' have any example at the moment

Maybe a better question; does the aws-termination-handler support launching a user-specified pod sidecar currently? if so do you have an example of that. 

Regarding the race conditions, I think that is something the user will need to maintain. I think the race-condition will be an edge case where the latest weights get transferred to S3. in my TF/PY container the SIGTERM can kill the training job and in the sidecar the SIGTERM can trigger the copying of the *latest* weights

**Comment by bwagner5** [comment]
I agree with @ruecarlo, handling via SIGTERM in the application container is the best way to accomplish this today either with a sidecar container in the same pod or directly in the application container. 

I'm not so sure it makes sense to include any additional functionality within aws-node-termination-handler since any checking pointing or application draining actions will be very application specific. The aws-node-termination-handler will be draining the node which will correspond to many different applications with, potentially, their own draining/check pointing processes. 

Another way to trigger a script or action without using SIGTERM is to configure webhook on aws-node-termination-handler. This has the advantage that you'll know that the node is actually being interrupted rather than just shutting down for some other reason (like a deployment). If this approach provides benefits to users, then we could add support for multiple webhooks so that you don't need to compromise your notification to trigger a custom action or maintain code to fan out to notifications and other actions.
