### ISSUE TITLE
Network usage

### ISSUE THREAD

**Issue by estahn** [aws/aws-node-termination-handler#258]
Unless I'm reading this wrong, `aws-node-termination-handler` seems fairly network heavy:

![image](https://user-images.githubusercontent.com/362174/93834620-d7efee00-fcbf-11ea-87d2-249c9330ca78.png)

Is there any explanation for this?

**Comment by bwagner5** [comment]
We're investigating this.  NTH's only network calls are the EC2 Instance Metadata calls every 2 seconds and the Drain call to the k8s control plane when a termination notice is received. 

It might be possible that cross-az traffic could be high if a Pod Disruption Budget is preventing a pod from being drained off of a node, since NTH will keep trying continuously to drain the node. But it seems all the pods are using a lot of networking, so I doubt all those nodes have termination notices and a PDB is preventing them from draining.

The EC2 Instance Metadata service is on the 169.254.169.254 address which may be recorded even though it's a local call to the instance the pod is running on.

**Comment by bwagner5** [comment]
1. Are all of the pods showing high network usage or is it just a subset of them? 

2. Do you have the prometheus metrics endpoint enabled? If so, what is the scrape interval configured on prometheus? 

3. Logs would be helpful to see if there is an error case being hit, or if this is just normal operation.

4. Lastly, tcpdumps on the instance would also help to see if there is additional network traffic coming from the NTH pods.

**Comment by estahn** [comment]
@bwagner5 I will need to dig a bit deeper into this. I think the Grafana dashboard might be a bit confusing. `Bandwidth received` seems to be total and not per second. So in this case it appears to be fine.

I will close this for now and reopen if I find this to be an issue.

Thanks for your response.
