### ISSUE TITLE
Unable to parse scheduled event end time

### ISSUE THREAD

**Issue by mikesplain** [aws/aws-node-termination-handler#315]
Hello! I was just looking at one of our instances running the aws-node-termination-handler after getting a ec2 degredation email about it.  I was curious if NTH had removed the instances since we have `ENABLE_SCHEDULED_EVENT_DRAINING` enabled.  

We are running `amazon/aws-node-termination-handler:v1.11.0` and  we're using kiam underneath for IAM access.  

```json
{"time":"2020-12-10T00:59:27Z","message":"Trying to get token from IMDSv2"}
{"time":"2020-12-10T00:59:27Z","message":"Got token from IMDSv2"}
{"time":"2020-12-10T00:59:27Z","message":"Trying to get token from IMDSv2"}
{"time":"2020-12-10T00:59:27Z","message":"Got token from IMDSv2"}
{"error":"parsing time \"\" as \"2 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"2\"","time":"2020-12-10T01:50:29Z","message":"Unable to parse scheduled event end time, continuing"}
{"event":{"EventID":"instance-event-0c6a1ed93bfc96fd4","Kind":"SCHEDULED_EVENT","Description":"instance-stop will occur between 28 Dec 2020 06:00:00 GMT and  because The instance is running on degraded hardware\n","State":"active","NodeName":"ip-10-223-202-136.ec2.internal","InstanceID":"","StartTime":"2020-12-28T06:00:00Z","EndTime":"2020-12-28T06:00:00Z","Drained":false},"time":"2020-12-10T01:50:29Z","message":"Adding new event to the event store"}
{"error":"parsing time \"\" as \"2 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"2\"","time":"2020-12-10T01:50:31Z","message":"Unable to parse scheduled event end time, continuing"}
{"error":"parsing time \"\" as \"2 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"2\"","time":"2020-12-10T01:50:33Z","message":"Unable to parse scheduled event end time, continuing"}
# This continues like this indefinitely, even after a pod restart
```

Let me know if any more info would be helpful!

**Comment by haugenj** [comment]
NTH doesn't actually terminate instances, it'll just drain and/or cordon them. To see if NTH handled this event correctly you can check the node to see if it's been tainted with `aws-node-termination-handler/scheduled-maintenance`.

This error is showing up because the maintenance event didn't include an end time. It continues to appear because it's logged during the event object creation, and we don't dedupe until we have the full event object. Maybe we should remove that log message, I'm not sure it's particularly helpful

**Comment by mikesplain** [comment]
@haugenj Right, my description skipped a couple of those draining steps, currently we have a process with node-problem-detector and the descheduler that take care of troubled instances similar to this. Sorry for that!

I just checked, the node is not tainted and is still triggering that log message. I've turned up logging to debug but wasn't able to get any more details.  When I check the event in the aws console, the start time and end time are both listed and identical, and noticed IMDS returning only `notBefore` which makes sense and seems like NTH takes care of here https://github.com/aws/aws-node-termination-handler/blob/5150b31c819a26c2cc80f812ffb0a0b317290b56/pkg/monitor/scheduledevent/scheduled-event-monitor.go#L96

Any other ideas so we can see why the node isn't being tainted properly?

**Comment by haugenj** [comment]
I would suspect it's because `NODE_TERMINATION_GRACE_PERIOD` is set too low, or not set at all (it defaults to 120 seconds). NTH won't perform the drain until `NODE_TERMINATION_GRACE_PERIOD` seconds before the start time of the event, so for your case it won't start the drain until Dec 28. Code handling that is [here](https://github.com/aws/aws-node-termination-handler/blob/5150b31c819a26c2cc80f812ffb0a0b317290b56/pkg/interruptioneventstore/interruption-event-store.go#L94-L107). 

Now I _definitely_ think we should remove or dedupe that error log, having that message log constantly for weeks is no good🙅

**Comment by jillmon** [comment]
This issue should be addressed with PR for https://github.com/aws/aws-node-termination-handler/issues/361
