### ISSUE TITLE
Skip draining nodes which have already been deleted

### ISSUE THREAD

**Issue by matt-demers** [aws/aws-node-termination-handler#331]
I am running the NTH in QueueProcessor mode, and am trying to work around this issue.

When a node is deleted by an external source, such as terminating the instance directly in the console, the NTH prints out the following error message:

```
Error when trying to list Nodes w/ label, falling back to direct Get lookup of node
There was a problem while trying to cordon and drain the node error="nodes \"ip-10-XX-XX-XX.ec2.internal\" not found
```

Since the node was already deleted from kubernetes by the time the NTH gets the message from the SQS queue, it fails to lookup the node through kubectl, and fails hard. It will then put the NTH into a CrashLoopBackoff until the autoscaling group's lifecycle hook heartbeat times out.

This is particularly a problem because I am trying to run another tool to perform a rolling update on the cluster. The tool will scale up the ASG, drain the old nodes, delete the old node from kubernetes, and then terminate the node. When it tries to terminate the node, it times out because the NTH is not able to process the lifecycle hook, so the tool must wait for the full heartbeat timeout of the lifecycle hook.

It would be nice if the NTH could just be configured to skip draining a node if the node is not registered with the cluster, and then delete the SQS message as normal.

**Comment by bwagner5** [comment]
Which version of NTH are you using?  In v1.11.1 we merged in a fix for https://github.com/aws/aws-node-termination-handler/issues/307 which would query the instance via the EC2 API and check if a DNS name is there, if it's empty (meaning the instance is terminated) it would skip. It looks like this may not work in your case since it looks like it's getting a dns name which means the instance is not terminated yet from EC2 perspective but is deleted from Kubernetes. 

It's probably okay to ignore the drain if the node can't be found in kubernetes. I just want to check in on the specifics of your cluster setup to make sure it hasn't been taken care of yet since there's been a lot of interest around removing some of these checks causing crash backoffs.

**Comment by matt-demers** [comment]
Ah yes I was running version v1.11.0. Upgrading to v1.11.1 fixes my issue. The node is shutdown externally and the NTH doesn't crash. 

Thanks for the help
