### ISSUE TITLE
How can we prevent from NTH to receive the events from different clusters?

### ISSUE THREAD

**Issue by diegosanchez** [aws/aws-node-termination-handler#340]
##### The context

We deploy NTH `v1.10` using the "Queue Processor" flavor. For this purpose we followed the instructions listed in the [README.md - AWS Node Termination Handler - Queue Processor \(requires AWS IAM Permissions\)](https://github.com/aws/aws-node-termination-handler#note-this-functionality-is-currently-in-beta) file.

Given that we have two clusters (staging and production) we created both queues _StgQueue_ and _ProdQueue_, respectively. Additionally, we configure the rule associated with the `aws.ec2`event to send events to the appropriate queue depending on the cluster target. The staging rule sends the events to  _StgQueue_ while the production rule sends to _ProdQueue_.

The staging and production clusters were created in the same aws account, and it can be changed.

##### Here is the thing: 
The NTH from staging/production cluster keeps receiving the `aws.ec2` events from production/staging cluster (mind the exchange of clusters).

##### The question:
Are there a way to prevent NTH from receiving events from different clusters?

###### Disclaimer:
We know it is **not** a NTH bug but a limitation of the [Spot Instance interruption notices](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#spot-instance-termination-notices). We just would like to known if some of you faced this problem before and how you come up with a solution/workarround.

**Comment by bwagner5** [comment]
As of NTH v1.11.0 we support a configurable tag value on the ASG so that NTH will only take action on nodes that are managed by the ASG with the corresponding tag. The messages will still be consumed by both NTH installs, but after describing the ASG tags, NTH will not take action if the ASG is not tagged w/ the configured value.

The config is called `managedAsgTag` in the helm chart values: https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler

So you could do something like this:

```
# Staging
$ helm upgrade --install aws-node-termination-handler \
  --namespace kube-system \
  --set enableSqsTerminationDraining=true \
  --set queueURL=https://sqs.us-east-1.amazonaws.com/0123456789/my-STAGING-queue \
  --set managedAsgTag="STAGING" \
  eks/aws-node-termination-handler

$ ... <CHANGE CLUSTER CONTEXT> ...    

# Prod
 $ helm upgrade --install aws-node-termination-handler \
  --namespace kube-system \
  --set enableSqsTerminationDraining=true \
  --set queueURL=https://sqs.us-east-1.amazonaws.com/0123456789/my-PROD-queue \
  --set managedAsgTag="PROD" \
  eks/aws-node-termination-handler
```

You'll probably want to upgrade NTH to v1.12.0 so that the docker image is pulled from the ECR Public Repo.  NTH versions < v1.11.2 still pull from DockerHub which can now be [rate limited ](https://www.docker.com/increase-rate-limits)

For context:
https://github.com/aws/aws-node-termination-handler/issues/272
https://github.com/aws/aws-node-termination-handler/pull/287
https://github.com/aws/aws-node-termination-handler/releases/tag/v1.11.0

**Comment by diegosanchez** [comment]
@bwagner5 We implemented the suggested solution successfully. Thanks for the advice about rate limit,  as well.
