### ISSUE TITLE
High Availability for queue processor mode

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#353]
The deployment for queue processor mode only has a single replica, and it's not configurable via Helm.

https://github.com/aws/aws-node-termination-handler/blob/23b97f40987f52a28d533bd7bba7a391d46e7e3b/config/helm/aws-node-termination-handler/templates/deployment.yaml#L10

Is running more replicas possible, or will they conflict?

**Comment by gabegorelick** [comment]
Thinking about this more, for ASG lifecycle hooks I think the lack of HA is mitigated by the fact that the ASG will wait for `HeartbeatTimeout` seconds before proceeding. So as long as Kubernetes reschedules the pod before then, you should be fine. 

But spot instance termination notifications are more time sensitive, so perhaps there's more of a need for HA there?

**Comment by bwagner5** [comment]
Multiple replicas should at least be configurable.  The reason it is 1 right now (it used to be 2), is because of https://github.com/aws/aws-node-termination-handler/issues/297. Duplicate webhooks are more difficult to handle on separate replicas. For example when a Spot ITN is triggered, you'll get the Spot ITN webhook, the ASG termination webhook, and the EC2 instance status change webhook. 

The plan to mitigate some of those dupes is to track nodes in-memory and not send hooks on the same node within some time period if they've already drained successfully.

**Comment by gabegorelick** [comment]
> The reason it is 1 right now (it used to be 2), is because of #297. Duplicate webhooks are more difficult to handle on separate replicas.

Does that mean that there is no issue running multiple NTH replicas if you don't have `webhookURL` set?

**Comment by bwagner5** [comment]
Sorry, very delayed response, but Yes, there is no issue running multiple replicas of NTH if webhookURL is not set (even if it is, as long as you don't mind getting duplicate events sometimes, it's still fine).  I merged a PR this morning to allow replicas to be configured with Helm.

**Comment by gabegorelick** [comment]
Thanks for the info. It's pretty common for Kubernetes tooling like this to do leader election when running multiple replicas. But I assume that's not necessary because SQS is used.

**Comment by bwagner5** [comment]
replicas are now configurable via helm in v1.13.1
