### ISSUE TITLE
Is there a way to delete drained nodes from the cluster completely after a period of time?

### ISSUE THREAD

**Issue by franz101** [aws/aws-node-termination-handler#358]
Whats the best practice here, would you recommend to set up the new spot instance with the same hostname?

**Comment by bwagner5** [comment]
It's not necessary to setup a replacement spot instance with the same hostname. K8s will schedule pods to the new node once it's available. But since the pods have already been drained, they'll likely be scheduled on other nodes already, unless you're running the cluster with very little headroom. 

As far as deleting drained nodes from the cluster after a period of time, there's currently not a way to do this, but I'm curious how the node would get into this state? If you're running NTH in IMDS mode with rebalance-recommendations enabled, then the node will only be cordoned, not drained (so that you don't have a provisioned node that isn't doing anything in your cluster). If you're using NTH in queue-processor mode and have your EC2 ASGs configured to work with rebalance-recommendations, then ASG would provision a new node to replace it, ASG would terminate the old node, NTH would cordon and drain the old node from the termination lifecycle hook. 

The only way I think nodes would get stuck in a drained state is if an operator drained the node manually, or PDBs were preventing a node from completely draining.  Curious to hear some more specifics into the problem you're trying to solve for and how we can help.

**Comment by franz101** [comment]
Thanks for your quick reply. I just recently started setting up my cluster. and I haven't set the host name on the instance. So it gets set up automatically and uses the internal ip. There is no reason why no to set a fixed hostname. 

Thanks for your curiosity.
I discovered aws-node-termination-handler afterwards I starting setting up the following structure:
As a prototype I have set up a spot instance with a template that has script which adds itself to my self hosted k3s cluster. Once the spot instance boots a lambda gets triggered through sns and adds its public ip to the security group.
Then I set up ASG to automatically spawn a new instance once it gets terminated. I use it mainly for a small data science cluster. I felt like documentation for the termination-handler was a bit advanced therefore I will take your words to heart and go through it a bit.  Basically what I have built is a sagemaker running on a single spot instance. :)

Let me know if should close this issue.
