### ISSUE TITLE
SQS messages deleted without being processed

### ISSUE THREAD

**Issue by azenk** [aws/aws-node-termination-handler#360]
When several nodes are being terminated at once, we've observed that some of the messages are deleted from the queue without being processed.

This seems to be due to NTH retrieving [up to two messages from SQS](https://github.com/aws/aws-node-termination-handler/blob/23b97f40987f52a28d533bd7bba7a391d46e7e3b/pkg/monitor/sqsevent/sqs-monitor.go#L143), [only processing the first](https://github.com/aws/aws-node-termination-handler/blob/23b97f40987f52a28d533bd7bba7a391d46e7e3b/pkg/monitor/sqsevent/sqs-monitor.go#L78) but passing both into `asgTerminationToInterruptionEvent` where [both messages are deleted](https://github.com/aws/aws-node-termination-handler/blob/23b97f40987f52a28d533bd7bba7a391d46e7e3b/pkg/monitor/sqsevent/asg-lifecycle-event.go#L114).

**Comment by haugenj** [comment]
This is a good callout. The easy fix would be to change the request to accept a max of 1 message, but I think we should go the extra mile and parse them into multiple events similar to how we're doing in scheduled-event-monitor.go. 

@azenk are you interested in picking this up? Otherwise I can take it on sometime next week
