### ISSUE TITLE
Metric counters don't report 0 to Prometheus

### ISSUE THREAD

**Issue by risinger** [aws/aws-node-termination-handler#374]
NTH does not report 0 when a metric has not been observed during runtime. Prometheus expects counters to report 0 when they are 0. If they are simply not reported, `rate` will report 0 when the metric is first reported, no matter the value. Because the first value is an observation, any alerting or visualization in Prometheus will either miss all errors/actions in the first scrape that has that metric or the alert/graphing needs to use the raw total number of observations during an NTH pod's lifetime. 

I realize this may well be a bug in OpenTelemetry, but it also seems possible the counters are not properly initialized in NTH. 

Here's a grafana graph to visualize the problem (`increase` is syntactic sugar for `rate` times the range selector): 

![image](https://user-images.githubusercontent.com/9733814/109185204-c672ac80-775d-11eb-88a7-6bfb35fe6481.png)

**Comment by haugenj** [comment]
From reading around, it looks like ideally we would initialize these metrics at the beginning when we set up the metrics server. We can do that for the error metrics, but the node metrics are trickier because they use labels with the node name which we don't know ahead of time. 

Perhaps we can init the error metrics early, and for the node metrics do a lookup to see if they're initialized before the first increment?

**Comment by drstevens** [comment]
Bump here per @bwagner5's suggestion in [slack](https://kubernetes.slack.com/archives/C0LRMHZ1T/p1638389268275200?thread_ts=1599723712.160800&cid=C0LRMHZ1T)

**Comment by stevehipwell** [comment]
@bwagner5 we're using the `(rate(actions_node{job="aws-node-termination-handler",node_status!="success"}[5m]))` query to trigger alerts and are getting our alerts replayed every 12 hours.

**Comment by stevehipwell** [comment]
@bwagner5 have you been able to look into this?

**Comment by cjerad** [comment]
This has been released in `v1.20.0`, chart version `0.22.0`
