### ISSUE TITLE
README recommends 3 distinct EventBridge rules but only 1 is needed

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#415]
For queue processor mode, the README mentions creating three EventBridge rules, with a target for each:

```
$ aws events put-rule \
  --name MyK8sASGTermRule \
  --event-pattern "{\"source\":[\"aws.autoscaling\"],\"detail-type\":[\"EC2 Instance-terminate Lifecycle Action\"]}"

$ aws events put-targets --rule MyK8sASGTermRule \
  --targets "Id"="1","Arn"="arn:aws:sqs:us-east-1:123456789012:MyK8sTermQueue"

$ aws events put-rule \
  --name MyK8sSpotTermRule \
  --event-pattern "{\"source\": [\"aws.ec2\"],\"detail-type\": [\"EC2 Spot Instance Interruption Warning\"]}"

$ aws events put-targets --rule MyK8sSpotTermRule \
  --targets "Id"="1","Arn"="arn:aws:sqs:us-east-1:123456789012:MyK8sTermQueue"

$ aws events put-rule \
  --name MyK8sRebalanceRule \
  --event-pattern "{\"source\": [\"aws.ec2\"],\"detail-type\": [\"EC2 Instance Rebalance Recommendation\"]}"

$ aws events put-targets --rule MyK8sRebalanceRule \
  --targets "Id"="1","Arn"="arn:aws:sqs:us-east-1:123456789012:MyK8sTermQueue"
```

However, the section heading ("Create an Amazon EventBridge Rule") and body copy ("Here is the AWS CLI command to create an Amazon EventBridge rule") are singular. I'm pretty sure a single rule with multiple sources and detail-types would work just fine [1], and it would be simpler to set up.

Example:
```sh
$ aws events put-rule \
  --name MyK8sNodeTerminationHandlerRule \
  --event-pattern '{"source":["aws.autoscaling","aws.ec2"],"detail-type":["EC2 Instance-terminate Lifecycle Action","EC2 Spot Instance Interruption Warning","EC2 Instance Rebalance Recommendation"]}"'

$ aws events put-targets --rule MyK8sNodeTerminationHandlerRule \
  --targets "Id"="1","Arn"="arn:aws:sqs:us-east-1:123456789012:MyK8sTermQueue"
```

[1] Values are OR-ed together: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns.html.

**Comment by brycahta** [comment]
True, only 1 rule is needed; however, I would disagree that this makes things simpler for everyone. Users just learning about this project/technology can see the clear relationship between `source` and `detail-type` for each notification and for those users only wanting to listen for Spot Interrupts can copy/paste those commands without parsing and editing the 1 rule.

If we are discussing the way it *should* be done, we call out that using Cloudformation, Terraform, etc. is recommended throughout Queue Processor setup.

> However, the section heading ("Create an Amazon EventBridge Rule") and body copy ("Here is the AWS CLI command to create an Amazon EventBridge rule") are singular

The original intent was to only include the EventBridge rule for ASG termination events per the ReadMe, "Here is the AWS CLI command to create an Amazon EventBridge rule so that **ASG termination events** are sent to the SQS queue created in the previous step". Either way-- this description should be updated.

**Comment by gabegorelick** [comment]
> Users just learning about this project/technology can see the clear relationship between source and detail-type for each notification

That is true. I suppose that has to be weighed against having 3x the commands to get started (or 3x the CloudFormation resources or whatever). 

Anyway, thanks for confirming that 1 rule is OK. If you feel strongly against consolidation in the README, that's fine.

**Comment by brycahta** [comment]
If you can validate the behavior using the single command, then I'm not opposed to including it. 

In theory, I don't see why there'd be issues (famous last words), but would like to be certain before suggesting to users.

**Comment by brycahta** [comment]
Resolving after adding clarifications. 

Feel free to open a PR with the consolidated command after testing and we can review.
