### ISSUE TITLE
How does node termination handler handle Pod Disruption Budgets?

### ISSUE THREAD

**Issue by clayvan** [aws/aws-node-termination-handler#433]
Does NTH support PDBs?
If a node enters a terminating state, the lambda will be invoked. If a pod cannot be evicted because it would violate a PDB, then the drain fails. The lambda will eventually hit the 15 minute timeout. At maximum an instance can remain in a WAIT state for 48 hours if it keeps receiving heartbeats.

Managed Node Groups docs says that it supports PDBs, but then also says it uses EC2 lifecycle hooks, which would mean it's still subject to at maximum a 48 hour wait state before the instance is terminated.

Cluster Autoscaler is able to support PDBs on scale in because it is a long running controller that checks deployment replicas and disruption budgets BEFORE sending a termination signal to the node.

How is everyone else handling long running pod disruption budget violations?

**Comment by bwagner5** [comment]
NTH in queue-processor mode would attempt to evict a node when an ASG lifecycle termination hook is received via EventBridge in the SQS queue configured for NTH. If there is a PDB violation during the eviction of the node, some pods should still be evicted. The message would remain on the queue for a retry. The amount of time a message stays on the queue can be configured when you setup the queue. 

It sounds like the case you're talking about is when 1 pod cannot be evicted on the node or the PDB will be violated. It's probably not the best PDB configuration if that is the case, you should probably up the number of pods in the deployment to leave some headroom to make this situation less of a concern. If 2 pods were on the node and you could only evict 1, then 1 should get evicted and would therefore get rescheduled elsewhere and then when NTH retried the node eviction, the other one would get evicted. 

I think there are ways you could make NTH retry past the 48 hour lifecycle hook timeout by setting the lifecycle hook to a cancel action on timeout rather the continue maybe? I'm not sure that would be a great idea for other reasons but it might be possible. For example, a spot ITN would not be able to cancel the lifecycle hook and would get terminated after 2 minutes no matter how long you try to wait. 

I think the best solution to this problem is to increase the number of replicas for the deployment so that the PDB isn't so fragile. Let me know if I'm missing a nuance to the problem you're describing.

**Comment by clayvan** [comment]
@bwagner5 Hey thanks for the information

If spot instances are used, then yeah the instance will be terminated no matter what, so the deployments will need to be able handle termination. For us, we use reserved instances, so I would expect us to keep the instance up as long as I need.

An example of a scenario:
- A K8s deployment has 3 replicas.
- A Pod disruption budget defines `maxUnavailable: 33%`
- A cluster admin is going to roll out a new AMI to 3 worker nodes.
- Uh oh, the docker registry is in a downtime.
- The ASG spawns a new instance, and sends a termination signal to an old instance.
- NTH Lambda gets invoked via lifecycle hook and evicts pods.
- 2nd instance gets terminated
- NTH Lambda gets invoked via lifecycle hook, but this time receives an error that it cannot evict pod because it would violate - PDB as the 1st instance wasn't able to pull the image for the new pod.
- Lambda execution max of 15 minutes times out, lifecycle hook continues and terminates the instance causing a PDB violation.
- ASG moves onto the 3rd instance, and causes a downtime because the node termination handler cannot stop an instance from terminating even if its violating a PDB.

Note: I haven't actually used NTH, but I use something very similar (cloudwatch rule + lambda + lifecycle hook)

**Comment by bwagner5** [comment]
NTH is not run in a Lambda function, so there is no 15 min timeout. NTH runs in the k8s cluster as a deployment. It's kind of a controller but doesn't watch any cluster resources, instead it's watching for termination events via EventBridge+SQS. 

I was incorrect on the lifecycle hook comment in the previous message. The max you can keep any instance after a terminating lifecycle hook has triggered is 48 hours. NTH will keep retrying the eviction request until the message retention period configured on the SQS queue has been reached. The retention period is configurable so you should also be able to retry up to the max which appears to be 14 days (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-basic-architecture.html), but the lifecycle hook will shut the instance down after 48 hours.

So it appears there is no way to hold on to an instance longer than 48 hours using ASG and lifecycle hooks.

**Comment by clayvan** [comment]
That's what I was afraid of ☹️ 

It appears that Managed Node Groups don't send the instance termination signal until all pods have been evicted, which I think is the right behavior, but it doesn't sound like NTH is the right tool to match behavior for self managed nodegroups.
https://docs.aws.amazon.com/eks/latest/userguide/managed-node-update-behavior.html

Honestly I'm pretty surprised this isn't talked about more considering the adoption of autoscaling + pod disruption budgets.

Thanks for the info, I'll try to post back to this thread if I come up with a creative solution.

**Comment by bwagner5** [comment]
I don't think there are any technical blockers to implementing the steps outlined in the managed node update behavior docs.  However, I'm not sure NTH is the right thing to handle that update process. But I do think NTH should be a little more flexible and extensible so that maybe a new controller could notice the AMI change and inform NTH to cordon and drain nodes via a label on a node or something.

**Comment by stevehipwell** [comment]
@bwagner5 my understanding is that with the [ASG instance refresh](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html) behaviour NTH can be used to mimic the behaviour of managed node groups now?
