### ISSUE TITLE
Question: How to handle rebalance-recommendation on EKS self-managed nodes

### ISSUE THREAD

**Issue by MRostanski** [aws/aws-node-termination-handler#458]
Hello,
We are using aws-node-termination-handler in IMDS mode. EKS nodes belong to a couple of ASGs and are all spot-type. 
However, we are struggling with handling the rebalance recommendation signal, just like the example below:

```
2021/06/25 06:57:01 INF Adding new event to the event store event={"AutoScalingGroupName":"","Description":"Rebalance recommendation received. Instance will be cordoned at 2021-06-25T06:57: 
 00Z \n","Drained":false,"EndTime":"0001-01-01T00:00:00Z","EventID":"rebalance-recommendation-3fe70e54ea057bbd417f70d69829913d9e791afeb972b00bfeaeeccfb7b1dfa5","InProgress":false,"InstanceID 
 ":"","Kind":"REBALANCE_RECOMMENDATION","NodeLabels":null,"NodeName":"ip-xxx-xxx-xxx-xxx.us-west-2.compute.internal","Pods":null,"StartTime":"2021-06-25T06:57:00Z","State":""}                  
 2021/06/25 06:57:02 INF Node successfully cordoned node_name=ip-xxx-xxx-xxx-xxx.us-west-2.compute.internal
```

In general, the spot node receivng this signal is being cordoned (as we want it to) and drained (as we want it to) ... however, the problem is that this signal means "a Spot Instance is at elevated risk of interruption" and is not always brought down, which leaves us with hainging unschedulable node.
I haven't come across some config that would revert the cordon after a while, and I even understand why it would be hard to achieve, but what is the suggested course of action then?

**Comment by bwagner5** [comment]
In order to handle a Spot Capacity Rebalance Recommendation without waiting on an ITN, you'll need to use NTH in [queue-processor mode](https://github.com/aws/aws-node-termination-handler#queue-processor) rather than IMDS mode. This will allow NTH to interact w/ the ASGs lifecycle hooks. 

You'll need to [Enable Capacity Rebalance on the ASG](https://docs.aws.amazon.com/autoscaling/ec2/userguide/capacity-rebalance.html). This will cause the ASG to launch a new instance when a rebalance recommendation is received and then start a termination after the new instance is running. If you setup NTH queue-processor mode, NTH will consume the rebalance event from the sqs queue and cordon + drain the node. It will then process the ASG termination lifecycle hook which will just have NTH check if the node has successfully drained yet. If it hasn't then NTH can hold the termination hook until the node finishes draining.  

The approach above is the best practice. However, it is still possible to use NTH in IMDS mode w/ capacity rebalance recommendations turned on in the ASG. When the rebalance event is observed on the node, NTH will perform a cordon and drain (if the `enableRebalanceDraining` is set to true), and the ASG will still launch a new node before terminating the node that received the rebalance event. But when using IMDS mode, NTH does not process the termination lifecycle hook. So if the node is taking a while to drain, then NTH can't stop the ASG from terminating the node prematurely.

**Comment by MRostanski** [comment]
Thank you! I understand now. 
I should also make note here for anyone that may come across the problem.

We were using self-managed nodes and the ASG was using Launch Template with Spot Instance Type defined directly in launch template options. Therefore I did not see the Capacity Rebalance option in ASG. Only a note "Your Auto Scaling group adheres to the launch template for purchase option and instance type" appeared in AWS console.

Once I have removed the instance type definition in Launch Template and set them up in ASG options, the "Capacity Rebalance" option was visible and possible to set up (and as @bwagner5 guessed, it was off before). Thanks again!
