### ISSUE TITLE
Frequent calls to DescribeInstances cause SQS backup and late notifications

### ISSUE THREAD

**Issue by mechanical-fish** [aws/aws-node-termination-handler#494]
`aws-node-termination-handler` seems to have the following logic (in `pkg/monitor/sqsevent/sqs-monitor.go`):

- Pull five messages from the SQS queue every 2 seconds with a 20-second-per-message visibility timeout
- Attempt to call the `ec2.DescribeInstances` API once per message (as part of the `retrieveNodeName` function). If the SQS queue is consistently full, this is 2.5 calls to `DescribeInstances` per second per queue.
- If `DescribeInstances` hits a rate limit, do not remove the message from the queue; instead leave it there to be retried 20 seconds later

We are now operating at sufficient scale that `DescribeInstances` is often hitting API rate limits -- I'm not sure those limits are published, so I'm not sure whether the 2.5-calls-per-second from each `aws-node-termination-handler` are a signifiant cause of our rate limiting, or merely one contributor. But once rate limiting begins we observe the following failure mode:

- `aws-node-termination-handler` will never pull more than 5 messages every 2 seconds.
- If it hits a rate limit the message stays on the queue to be redelivered 20 seconds later.
- The queue gets backed up. We consistently observe 40-50 messages in flight on our busiest SQS queues, though never more than 50 (note that 5 messages * 20 seconds / 2 seconds = 50 messages). There is often a backup of hundreds of messages and the wait times are 50 seconds to 300 seconds or more.
- At this point the majority of messages are handled so late that the instances are gone from EC2. The "good" news is that, when `DescribeInstances` manages to get through to the API, the message for an already-terminated instance gets deleted from the backed-up queue. The bad news is that it's way too late to warn Kubernetes by that point, so we are experiencing sudden unexpected failure of Kube pods.

I can think of a couple ways to change this code to help avoid this problem:

- Stop making so many calls to `DescribeInstances`. The purpose of these calls is to translate EC2 instance IDs to node names. Instance IDs are said to be unique (and are certainly vanishingly unlikely to be reused in rapid succession) and private DNS names are not mutable, so this mapping cannot change and can be cached -- we can periodically call `DescribeInstances` for all instances and cache the results.
- Make the number of SQS messages retrieved per 2-second cycle into a configurable parameter that can be tuned along with the number of workers. I'm not even sure why we fetch so few messages each time, except as a means of throttling the rate of `DescribeInstances` API calls, which could be managed differently as suggested above.

**Comment by bwagner5** [comment]
Hey @mechanical-fish ! Thanks for raising this issue! 

- As a work around for NTH to pull more messages, you can increase the replica count as a [helm parameter](https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler#aws-node-termination-handler---queue-processor-mode-configuration) or through kustomize. That will obviously put more strain on the DescribeInstances limit you are hitting but the messages will be pulled faster.  

I agree w/ the longer term solutions you propose. We can definitely increase the number of messages that NTH can pull at one time ([the max is 10](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#API_ReceiveMessage_RequestParameters)) and cache DescribeInstances calls. 

DescribeInstances does have a published request rate limit [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html#throttling-limits-rate-based) which is 10 QPS w/ a 50 QPS burst (token bucket).

**Comment by bwagner5** [comment]
I went ahead and put up the PR for increasing the max messages to 10. 

I think we also need to dynamically adjust the VisibilityTimeout when processing the message since most nodes will take longer than 20 seconds to drain. We can also retry a bit faster when rate limited by adjusting the visibility timeout in that case.

**Comment by ngoyal16** [comment]
@mechanical-fish we also facing same issue i have added caching for instance id and nodename to reduce the describe calls.

**Comment by snay2** [comment]
Our cache implementation should have the following characteristics:

1. **Reduce the QPS rate** of `DescribeInstances` calls while processing queue messages
1. **Memory consumption scales linearly**, both up and down, with the size of the k8s cluster
   * Specifically, old data should be removed from the cache soon after it becomes obsolete
1. Have a **configurable invalidation frequency** so customers can tune it per their cluster volatility or their AWS account API rate limits
   * A cluster with high node turnover or rapid scaling up/down may need to refresh the cache more frequently

One way to do this is to create a custom `DescribeInstances` provider that queries (on a configurable interval) to get the necessary information about all instances in the cluster or all ASGs that NTH is monitoring. Then the implementation of `retrieveNodeName` uses this provider instead of calling the `DescribeInstances` API directly.

This is a form of the ["constant work" pattern](https://aws.amazon.com/builders-library/reliability-and-constant-work/). Using such a pattern improves system stability under high load and unusual traffic patterns, such as a large influx of queue messages or a backed-up queue. Those circumstances will then not cause spikes in `DescribeInstances` calls that might exceed the rate limit. Rather, NTH will regularly call `DescribeInstances` on a predictable cadence. It may result in doing more work than necessary, but we trade off that extra work for more predictable performance under load.

**Comment by ngoyal16** [comment]
@snay2 sure i am happy to help on same.

**Comment by bwagner5** [comment]
That's probably right, that we can rely on time based eviction.

**Comment by ngoyal16** [comment]
@bwagner5 go-cache module added

**Comment by ngoyal16** [comment]
I have one more question regards setting this up . currently we are running 3 eks cluster in single region in a account should we use single queue for all of them or different for each..

**Comment by snay2** [comment]
@ngoyal16 Best practice is one queue per cluster. That avoids unnecessary processing and also prevents situations where NTH tries to handle messages from another cluster that it can't actually influence.

**Comment by snay2** [comment]
@mechanical-fish I look forward to hearing what you learn. If you think the additional logging would be beneficial to other customers as well, please do open a PR with it!

And yes, let's design the cache so it can support multiple data sources of instance information.

**Comment by snay2** [comment]
@ngoyal16 I don't have experience with this particular configuration, but the general best practice would be to have one queue per cluster, to avoid ambiguities like this that could arise from naming or IP address collisions across clusters. NTH doesn't have disambiguation logic for that kind of scenario; if you think it would be worthwhile to add it, feel free to open a separate issue as a feature request and we can discuss it with the community there.

**Comment by mechanical-fish** [comment]
Thanks for the prompt attention to #498 ! 

My second PR is https://github.com/aws/aws-node-termination-handler/pull/506 which I believe has actually addressed our immediate problems.

If and when #506 lands, it introduces an internal data structure, the `NodeInfo` struct, which looks like a good candidate for prefetching-and-caching using the `go-cache` module. That would address the issue we're discussing and make NTH even more API-efficient.

**Comment by mechanical-fish** [comment]
PRs #498 and #506, together with an increase to our API rate cap, have sufficiently lowered the urgency of this issue for my team that I haven't had further time to work on it. 

I still think it would be fine to use e.g. `go-cache` and a strategy of periodically fetching `NodeInfo` information to reduce the number of API calls required during high-traffic periods when many instances are terminating at the same time. But the case for such a feature is harder to make now that nearly every one of our terminating instances can be handled with one API call.
