### ISSUE TITLE
Refactor Helm chart

### ISSUE THREAD

**Issue by stevehipwell** [aws/aws-node-termination-handler#518]
**Describe the feature**
I'd like to refactor the Helm chart to make it more idiomatic and to improve the usability.

**Is the feature request related to a problem?**
n/a

**Describe alternatives you've considered**
n/a

**Comment by jillmon** [comment]
Hello @stevehipwell, how is your progress on this issue going so far? We've assigned the issue to you. Please feel free to reach out if you have any questions or need more clarification.

**Comment by stevehipwell** [comment]
@jillmon I was waiting on confirmation that a SemVer minor update was wanted? Assuming that's the case I'd also like to know if the project would be happy with deprecating values, if required for consistency, like was done in the LB controller chart.

**Comment by bwagner5** [comment]
ah yes, sorry @stevehipwell  Yes, a minor version update is preferable to maintain backwards compatibility. 

I think deprecating values is fine. I'm not sure how LB controller did this?  

Just a note: We are planning on doing a v2 of aws-node-termination-handler that has a slightly different architecture that should drastically simplify the helm chart and configuration in-general. We don't have a timeline yet on v2.

**Comment by stevehipwell** [comment]
@bwagner5 thanks for the response. A v2 sounds interesting, is it going to be queue only? Slightly off topic but is there any info on how NTH will align with Karpenter moving forwards?

**Comment by bwagner5** [comment]
Yes, v2 would be queue-only. I'll have a more detailed design out probably in January and we're planning on doing a community meeting where we'll present the plan for v2.  

As for Karpenter and NTH, Ellis and I have talked extensively about making Karpenter and Spot work seamlessly w/ NTH. It's a little difficult right now since NTH does require the infrastructure to be setup. But I think the v2 plan is related here. V2 will look a little more like Karpenter in terms of having a CRD and the ability to create logical "Terminators" (just like Karpenter has Provisioners). It may be possible to instantiate an NTH control loop directly within Karpenter and install the NTH CRDs w/ the Karpenter install. Nothing set in stone yet, but this is the general direction we are working towards.  

I'd love to get your thoughts @stevehipwell about this general plan!

**Comment by stevehipwell** [comment]
@bwagner5 looking forward to hearing more about the v2.

I'm loving the idea of logical terminators, and would be really happy if spot terminations could be treated differently to instance refresh. Having terminators grouping events and processing the instances as a group based on rules would solve so many problems. The queue(s) could be validated with a webhook based on the CRDs so it'd be clear to the users if NTH was going to work.

Is there any scope to look at CA integration to disable scale downs when there are pending termination events?

For Karpenter integration I was thinking that using NTH as a dependency and adding the spot controller loop inside Karpenter would be a good pattern. Obviously this would need the queue to be configured separately, but I don't think this'd be a problem especially if it was tied to CRDs as these would be opt in. Could Karpenter use NTH logic for launch template changes too?

**Comment by bwagner5** [comment]
> Is there any scope to look at CA integration to disable scale downs when there are pending termination events?

I'm not sure on the CA integration to disable scale downs. That sounds kind of hard and could backfire with a large number of ASGs.  Maybe if you'd disable scale downs based on the localized terminations of the ASG. I haven't thought about this at all.  If you have a clear use-case, can you describe it? 

> Could Karpenter use NTH logic for launch template changes too?

Probably not. Karpenter will probably use a separate mechanism to perform updates like that. We're currently working on defrag logic in Karpenter which might be more related work to the update strategy that Karpenter might eventually use. NTH would only be for Spot in Karpenter since Karpenter already handles cordon and draining in the normal termination case.

**Comment by stevehipwell** [comment]
I'm currently working through this and hope to open the PR later on. My current approach is to make it technically a breaking change, only for non-idiomatic use and Helm v2; but we can discuss this when the PR is opened.
