### ISSUE TITLE
Question: Can NTH kill notReady nodes?

### ISSUE THREAD

**Issue by darkgordon** [aws/aws-node-termination-handler#530]
**Describe the feature**
Hello !, hope everything is going well, I am recently using Node Termination Handler inside my sandbox k8s cluster, deployed by Kops and its working great, when an spot interruptions occurs using aws FIS experiments.
So I have the following question, can be Node Termination Handler used to terminated nodes when its detects some problems that lets some nodes in NodeReady status, for example when a node have the following taints: node.kubernetes.io/unreachable:NoSchedule, MemoryPressure or DiskPressure 
I Don’t know if this kind of remedy is inside Node Termination approach 

Any advice or documentation I will appreciate it, 
Have a nice day 😊 

**Describe alternatives you've considered
I dont know any alternative product

**Comment by bwagner5** [comment]
Hello! Thanks for posting this issue and glad to hear NTH is working well on kOps! Unfortunately NTH does not drain a node due to Memory or Disk Pressure (or any other k8s status). The only events that NTH will cordon and drain nodes for are events from AWS like Spot Interruption Termination Notices, Rebalance Recommendations, ASG lifecycle hooks, etc.

**Comment by darkgordon** [comment]
Okay, thank you very much @bwagner5 
have a nice day
