### ISSUE TITLE
Pods can be evicted to nodes that are about to be cordoned and drained

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#537]
**Describe the feature**
Let's say you've spun up a new ASG and are deleting the old one. In response to the ASG deletion, I would want NTH to cordon all nodes and only then start draining. My understanding of the current behavior is that NTH runs the cordon + drain concurrently on nodes, which means that pods can be evicted to nodes that haven't yet been cordoned, but will be very soon. 

In my testing, I see pods sometimes getting spun up on nodes for ~30s and then evicted.

**Is the feature request related to a problem?**
Placing pods on nodes that are about to be evicted leads to excessive churn and slows down ASG updates since now we have to spend more time evicting the pod again.

**Describe alternatives you've considered**
Run NTH in cordon-only mode, wait until all nodes are cordoned, and then run something that drains cordoned nodes.

I can understand how if NTH is only looking at per-instance events, it wouldn't have a high level picture to optimize its execution across multiple nodes. I guess it could wait a configurable amount of time after cordoning a node before draining starts. That way, it would have time to receive the other instance termination events and cordon the nodes.

**Comment by bwagner5** [comment]
This is an interesting use-case, a mass termination. I believe we currently have 10 worker routines in NTH on the cordon and drain part, so it probably works okay if there are 10 or less nodes (there could be some variable latency in network calls that might affect the 10 node case too). But I could see us breaking up the cordon and drain flows so that all nodes are cordoned within a batch before proceeding to drain. I believe if an ASG is deleted, the nodes will try to gracefully terminate and so we should get the individual termination lifecycle hooks, but catching the ASG deletion might allow us to further optimize the draining process.

**Comment by gabegorelick** [comment]
>  I believe if an ASG is deleted, the nodes will try to gracefully terminate and so we should get the individual termination lifecycle hooks

Correct. The lifecycle hooks work basically the same as a rolling update with batch size of 100%.

> But I could see us breaking up the cordon and drain flows so that all nodes are cordoned within a batch

Doing it per batch is probably easiest, but that's still suboptimal for rolling updates since you're going to end up placing pods on nodes that are in all likelihood about to be rolled in a future batch. 

> but catching the ASG deletion might allow us to further optimize the draining process.

Also instance refresh. I think NTH should be able to catch that and recognize that all nodes should be cordoned immediately. 

It would also be nice to detect rolling updates initiated by CloudFormation, Terraform, CodeDeploy, etc, but I recognize that may not be feasible.
