### ISSUE TITLE
Annotate drained pods indicating the pod was deleted by aws-node-termination-handler

### ISSUE THREAD

**Issue by nclaeys** [aws/aws-node-termination-handler#541]
**Describe the feature**
It would be useful to annotate the drained pods with something like: aws-node-termiation-handler/SpotInterruption = timestamp
This would simplify determining the cause of a pod termination inside our operator which is watching the pods.

**Is the feature request related to a problem?**
We get a lot of questions from our users about why their pod fail from time to time. Many of those cases are related to spot termination, which is at the moment difficult to diagnose. We have an operator watching the pods we create and do some logic to display to the user why the pod failed. For us it is at the moment tricky and time consuming to determine whether a pod was terminated by a user or due to spot termination, which is why we want to build this logic. 

**Describe alternatives you've considered**
We considered several alternatives, while not wanting to rebuild/fork this project:
- Creating a watcher on nodes nodes and when they are tainted, annotate the affected pods ourselves. We are not guaranteed that we always get the node update if our operator would crash etc... 
- Similarly we could add a webhook to do something as described above, but this feels wrong. 
- When deciding the failure reason of a pod, look up whether the node is tainted. This is simple to implement, the node will always exist when we get an event for a pod. Downside here is that node information is cached, thus we might see stale data. Additionally there might be race conditions to decide whether the pod is killed by a user or spot termination

**Comment by bwagner5** [comment]
I'm not sure adding an annotation on a pod would work very well either. If your operator crashed or was offline for a period of time, the pod will likely be gone already since eviction will trigger a pod deletion after it's terminated. Annotating pods as they are deleted seems a little heavy for the drain process, for example draining a large node that's running 100's of pods. We'd need to make a lot of API calls just to annotate the pods we're draining. 

Have you tried looking at the events that NTH emits for node draining? You shouldn't miss those depending on how long the API server is configured to keep events. If your operator catches pods that are terminating, pulls the node info, and consumes the events, I think you could tie a pod reason for eviction back to a node drain event.
