### ISSUE TITLE
[Question] Graceful Node Shutdown in k8s 1.21

### ISSUE THREAD

**Issue by yongzhang** [aws/aws-node-termination-handler#548]
Hi, 

I noticed this https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/ recently, is it a native replacement for aws node termination handler?

**Comment by stevehipwell** [comment]
@yongzhang graceful node shutdown only works in the context of a single node while NTH has a cluster level view. Although the current solution doesn't make full use of this high level view I think (@bwagner5 correct me if I'm wrong) there are plans to improve this. That said NTH could potentially allow the graceful node shutdown logic to be used on a node once NTH approves the lifecycle event.

**Comment by bwagner5** [comment]
It's possible that NTH could use the graceful shutdown feature (which in-turn wraps around systemd's inhibitor locks which can delay shutdown). The problem NTH is addressing is the amount of time the kubelet has to drain pods from the node as soon as a Spot ITN is received. So NTH would still need to catch that signal and start the node's shutdown process.  The configuration for the graceful shutdown is directly in the kubelet, so there would need to be a mechanism on your nodes where you can configure the delay cluster-wide, similar to NTH's `nodeTerminationGracePeriod` configuration. 

As far as NTH looking at the full state of the cluster... That's probably an over characterization of what it actually does, but NTH will retry draining a node when it encounters a PDB violation with the hope of new pods being spun up elsewhere to bring the PDB back to where NTH can drain pods. 

If NTH still needs to be in the mix to perform the cordon and drain, I'd be hesitant to switch to using the graceful node shutdown mechanism because of the on-node configuration required.
