### ISSUE TITLE
Unusually high bandwidth usage

### ISSUE THREAD

**Issue by FurkanTheHuman** [aws/aws-node-termination-handler#554]
In my two node cluster aws-node-termination-handler is using too much bandwidth. By "too much" I mean 7MB/s - 10MB/s. 
I get these numbers from prometheus(node exporter). Not sure if this is the expected behavior but from the description of this project, I believe that it shouldn't need any traffic at all.    

**Application Logs**
	dry-run: false,
	node-name: ip-<some ip>me-south-1.compute.internal,
	metadata-url: <some ip>,
	kubernetes-service-host: 172.20.0.1,
	kubernetes-service-port: 443,
	delete-local-data: true,
	ignore-daemon-sets: true,
	pod-termination-grace-period: -1,
	node-termination-grace-period: 120,
	enable-scheduled-event-draining: false,
	enable-spot-interruption-draining: true,
	enable-sqs-termination-draining: false,
	enable-rebalance-monitoring: false,
	enable-rebalance-draining: false,
	metadata-tries: 3,
	cordon-only: false,
	taint-node: false,
	json-logging: false,
	log-level: info,
	webhook-proxy: ,
	webhook-headers: <not-displayed>,
	webhook-url: ,
	webhook-template: <not-displayed>,
	uptime-from-file: ,
	enable-prometheus-server: false,
	prometheus-server-port: 9092,
	aws-region: me-south-1,
	queue-url: ,
	check-asg-tag-before-draining: true,
	managed-asg-tag: aws-node-termination-handler/managed,
	aws-endpoint:

These are the images taken from grafana
NOTE: when kube-proxy inccreases so does NTH and aws-node 
![Screenshot from 2022-01-03 13-53-54](https://user-images.githubusercontent.com/22262446/147924347-265c1f61-1c96-48a2-80f7-390978a94cff.png)
 ,
![Screenshot from 2022-01-03 13-54-07](https://user-images.githubusercontent.com/22262446/147924364-47a18e87-e607-4d1b-ba0e-34173992fc69.png)

**Environment**

* NTH App Version: public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.13.0
* NTH Mode (IMDS/Queue processor): No idea what this is
* OS/Arch: the one in the helm chart
* Kubernetes version: v1.19.13
* Installation method: helm

**Comment by bwagner5** [comment]
Hello! You're seeing a common reporting issue where pods using `hostNetworking` are reporting network metrics of the root network namespace which they reside in, which is a shared namespace that most traffic egresses through (depending on the setup). NTH is actually using very little network bandwidth. 

You're using NTH in IMDS mode which means it runs as a Daemonset and polls the Instance MetaData Service (IMDS - 169.254.169.254) to check for spot interruption notifications. You can reconfigure the NTH to not run DS pods with HostNetworking via a helm argument. NOTE if you change this, and have IMDSv1 disabled and are only using IMDSv2, you will need to configure the hop count for IMDSv2 to 2.  

https://github.com/aws/aws-node-termination-handler/blob/main/config/helm/aws-node-termination-handler/README.md#:~:text=false-,useHostNetwork,-If%20true%2C%20enables

Another way to clean up the graphs is to run NTH in Queue-Processor mode which runs one Deployment of NTH rather than a DaemonSet and uses a user configured SQS queue to monitor for Spot Interruptions. 

https://github.com/aws/aws-node-termination-handler/blob/main/README.md#queue-processor

**Comment by FurkanTheHuman** [comment]
Is there any advantage of disabling hostNetworking? If it is just the network of node and a misleading metric, there is no reason for me to change it.

**Comment by bwagner5** [comment]
Disabling hostNetworking is a good practice for security reasons. NTH has a low surface area and only listens to network connections when the prometheus server is on, so the risk is fairly low. If you change NTH to not use hostNetworking, you will have to change the IMDS hop count for your nodes.
