### ISSUE TITLE
Can webhook fire as soon as the notification is received, rather than waiting for cordon/drain to finish?

### ISSUE THREAD

**Issue by jazzdan** [aws/aws-node-termination-handler#572]
While it is helpful to know, after the fact, that an instance was interrupted and why, it can also be helpful to know before/during an instance interruption. For example: the node termination handler might fail to drain a node, causing an issue. Glancing at your Slack channel wouldn't show any messages in this case. It would be helpful to know that an instance drain was started, but hasn't finished, in this case.

Alternatively I guess we could set up another SQS queue with another set of Eventbridge resources, but that seems like a lot of work when the node termination handler already has all of this information, it's just delivering it too late.

Thanks for all your work on this project!

**Comment by evandam** [comment]
Hey @jazzdan can this issue be reopened?

I'm facing a similar situation, where we aren't seeing Slack messages and unsure if it's because of something like this or an unrelated issue.

Being able to see when the notification is received, even with some debugging info when enabled, would be really helpful.

**Comment by jazzdan** [comment]
Hey @evandam I don't have permission to re-open, sorry!

**Comment by evandam** [comment]
No worries, @snay2 able to help out? 🙏

**Comment by snay2** [comment]
This is probably a better usecase for metrics and alarms than for NTH's webhooks. Depending on the things you want to monitor, I'd recommend using CloudWatch or Prometheus to dial in on the failure cases where you need manual intervention and set up alarms around those. You can get a more robust operational posture that way.

Also, the reason for re-opening this issue was addressed separately in #626 (enabling NTH to monitor rebalance events in the customer's cluster).
