### ISSUE TITLE
Can't drain and cordon a node with daemonsets

### ISSUE THREAD

**Issue by paulojmdias** [aws/aws-node-termination-handler#593]
**Describe the bug**
Hi 👋 
We have NTH deployed in some EKS clusters, but when an event SPOT_ITN occurs, they can't drain or cordon the node with the following error:
"There was a problem while trying to cordon and drain the node"

For us, we want to gracefully delete all the pods in the node which will be terminated, even if it's a part of a daemon set.

**Steps to reproduce**
Have daemonsets running in some node and use NTH with the following variables:

```
ASSUME_ASG_TAG_PROPAGATION        = false
CHECK_ASG_TAG_BEFORE_DRAINING     = false
CORDON_ONLY                       = false
DELETE_LOCAL_DATA                 = true
DRY_RUN                           = false
EMIT_KUBERNETES_EVENTS            = true
ENABLE_PROBES_SERVER              = true
ENABLE_PROMETHEUS_SERVER          = true
ENABLE_REBALANCE_DRAINING         = false
ENABLE_REBALANCE_MONITORING       = false
ENABLE_SCHEDULED_EVENT_DRAINING   = true
ENABLE_SPOT_INTERRUPTION_DRAINING = true
ENABLE_SQS_TERMINATION_DRAINING   = false
EXCLUDE_FROM_LOAD_BALANCERS       = true
IGNORE_DAEMON_SETS                = false
JSON_LOGGING                      = true
LOG_LEVEL                         = "info"
METADATA_TRIES                    = 3
NODE_TERMINATION_GRACE_PERIOD     = 120
POD_TERMINATION_GRACE_PERIOD      = -1
PROBES_SERVER_ENDPOINT            = "/healthz"
PROBES_SERVER_PORT                = 8081
PROMETHEUS_SERVER_PORT            = 8082
TAINT_EFFECT                      = "NoSchedule"
TAINT_NODE                        = true
UPTIME_FROM_FILE                  = "/proc/uptime"
WORKERS                           = 10
```

**Expected outcome**
We want to gracefully delete all the pods in the node which will be terminated, even if it's a part of a daemon set without errors and without ignoring daemon sets.

**Application Logs**
```
{"level":"error","error":"cannot delete DaemonSet-managed Pods (use --ignore-daemonsets to ignore): kube-ingress/nginx-ingress-controller-6w8c9, kube-system/aws-node-khtzx, kube-system/aws-node-termination-handler-4x878, kube-system/datadog-agent-j9nq4, kube-system/kube-proxy-gd4sv, kube-system/node-local-dns-cswcf, logging/fluentd-9fhtn, monitoring/telegraf-daemonset-nl54s, node-configuration-daemonset/node-patch-installer-wm4vk, tracing/jaeger-agent-6gfdg","time":"2022-02-18T15:09:41Z","message":"There was a problem while trying to cordon and drain the node"}
```

**Environment**

* NTH App Version: v1.15.0
* NTH Mode (IMDS/Queue processor): IMDS
* OS/Arch: Amazon Linux 2/amd64
* Kubernetes version: 1.21.1
* Installation method: Kubernetes Manifest

**Comment by laghoule** [comment]
@paulojmdias oh sorry for the misunderstanding. 
As I see here: https://github.com/aws/aws-node-termination-handler/blob/main/pkg/node/node.go#L117 they use the `kubectl drain` package, so no easy way to handle this. Maybe you can use the `taint_node` option, and your app can watch for the taint on the running node. This way, the deamonset will not restart a new pod, because there's no toleration. Just my 2c.

**Comment by AustinSiu** [comment]
@paulojmdias thank you for raising the issue. @laghoule is correct in that we use `kubectl drain`, and per [the documentation](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain), it will not delete any daemonset pods, regardless of setting `--ignore-daemonsets` (`IGNORE_DAEMON_SETS` flag). 

A short-term solution, since you're on Kubernetes version 1.21, is to leverage the [Graceful Node Shutdown feature (beta in 1.21)](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/), while setting `IGNORE_DAEMON_SETS=true` (this will ignore daemonset-related _errors_) as a workaround. This allows you to drain all of your pods after receiving the node termination signal, but with a configurable grace period to postpone termination while draining. For your daemonset pods, you can configure them as `critical pods` if you need them to run during the termination of your other pods.

The long-term solution is to replace `kubectl drain` with an implementation to invoke the eviction API directly.
