### ISSUE TITLE
Document the need for ignore-taint configuration setting when using cluster-autoscaler 

### ISSUE THREAD

**Issue by nclaeys** [aws/aws-node-termination-handler#648]
**Describe the feature**
We encountered issues with the taint specified: aws-node-termination-handler/spot-itn and our cluster-autoscaler configuration.
I am not sure if it fits in this project but it might be worth specifying that in order to configure the cluster-autoscaler correctly, you should add the aws-node-termination-handler/spot-itn to the ignore-taint option.

**Is the feature request related to a problem?**
When scaling down to 0 due to a spot interrupt, we noticed that the autoscaler remembered the taint, which caused that a scale-up never happened since our pods do not tolerate the aws-node-termination-handler/spot-itn taint. The only way to fix this with the default autoscaler configuration is to restart the autoscaler.

**Describe alternatives you've considered**
/

**Reproduce the issue**
- taint all nodes for a specific launch template with a aws-node-termination-handler/spot-itn=somevalue:NoSchedule
- delete a pod that should use the specific launch template
- No scale up will happen because of the taint

**Comment by AustinSiu** [comment]
Hi @nclaeys, I wasn't able to reproduce the issue after sending spot interruptions to trigger the taints. Can you help provide any other details? In particular,
> we noticed that the autoscaler remembered the taint

Can you share how you observed this, or if this is expected behavior from Cluster Autoscaler's side?

If this is an issue with Cluster Autoscaler that could be triggered by any custom taints, not just NTH's, then the documentation for recommended usage of `--ignore-taints` may be more visible and helpful in the Cluster Autoscaler project instead.
