### ISSUE TITLE
cannot use when restricting access to metadata service

### ISSUE THREAD

**Issue by cdaniluk** [aws/aws-node-termination-handler#74]
In order to prevent pods from assuming the IAM role of the node, we restrict access to the metadata service for pods as follows:

```
yum install -y iptables-services
iptables --insert FORWARD 1 --in-interface eni+ --destination 169.254.169.254/32 --jump DROP
iptables-save | tee /etc/sysconfig/iptables 
systemctl enable --now iptables
```

This is recommended in the [AWS EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/restrict-ec2-credential-access.html) for worker nodes.

When running the termination handler, the following is logged:

```
2020/01/28 00:33:47 Request to instance metadata failed. Retrying.
2020/01/28 00:34:17 Error getting response from instance metadata  Get http://169.254.169.254/latest/meta-data/spot/instance-action: dial tcp 169.254.169.254:80: i/o timeout
```

Mostly logging this so that other people who run into the same know this isn't supported.. but are there any plans to add support for gathering the termination events through CloudWatch events when restricting access to the metadata service? Or should we just use an alternate termination handler?

**Comment by mattrandallbecker** [comment]
Definitely makes sense if you block metadata this handler would not work.

Looks like that documentation recommends that you block the entirety of metadata service via a userdata script such that it's not accessible on the host.  You could not use an instance profile and not assign the metadata credentials any permissions. Then you wouldn't need to prevent assuming the role or block metadata.

Alternatively, we are investigating support for the [instance metadata store v2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) which has authentication, you could then use a secret store or configure the handler to use the token to get metadata information. https://github.com/aws/aws-node-termination-handler/issues/22

Lastly, we did investigate supporting CloudWatch events as a means of getting instance notifications but that would require a different approach than this repo currently employs.  Likely via a centralized controller listening for events rather than a distributed daemonset, but we wanted to avoid having to set up any AWS specific permissions to get the project to work for ease of use.

**Comment by marcincuber** [comment]
I have the same scenario as @cdaniluk. I think this is a massive issue with this aws-node-termination-handler.

**Comment by mattrandallbecker** [comment]
@marcincuber 

Unless I'm misunderstanding something I'm not sure it makes sense to drop all metadata routes if your instance profile has no permissions.  Similarly, I'm not sure why you would need instance profile permissions if you are blocking metadata as you wouldn't be able to use them.

Is there some use case I'm not seeing? If not, I'll speak with the EKS team about changing their documentation.

**Comment by marcincuber** [comment]
@mattrandallbecker if there are no permissions attached to worker nodes then that is absolutely correct. Bare in mind that the documentation has been written after "IAM roles for service accounts" feature release. So, perhaps there is another use case that I am not seeing as well.

**Comment by cdaniluk** [comment]
@mattrandallbecker Worker nodes must have an instance profile with at least two managed policies attached. And those managed policies allow you to describe most VPC/EC2 resources, which is certainly not something you'd want all pods to be able to do.

Also, the iptables rules only affect forwarded traffic--effectively, pods only. It would not affect the instance's ability to access its own metadata services. So it does make sense to use this when an instance profile is attached.

Since there are alternative implementations, I don't think this is a huge deal. Could you indicate in the docs somewhere that _if_ you are blocking pods from the metadata service, you need to use one of the alternative implementations? Most people are naturally going to gravitate toward the AWS provided handler. Updating the docs will save them the confusion of installing it and trying to figure out why it doesn't work..

**Comment by mattrandallbecker** [comment]
Yep, totally understand the issue now, I was missing that those managed policies were required and seem to have extensive permissions beyond what is necessary.  We'll update the documentation shortly and investigate alternatives to making this work and hopefully provide either updated setup instructions or change our approach.

**Comment by mattrandallbecker** [comment]
Updated documentation to mention metadata access is required and we are going to look into ways to limit access to credential paths

https://github.com/aws/aws-node-termination-handler/pull/84

**Comment by mattrandallbecker** [comment]
ok turns out that resolution was a bit pre-emptive, turns out with host level networking set to true on the pod we still get access to the metadata service so i'll create a pull request to add that to our helm chart then this should still work even if you run the recommended iptables block

default configuration
```
mrbecker@local  ~  kubectl logs aws-node-termination-handler-9wwh6 --namespace kube-system
2020/01/31 22:36:30 Kubernetes Spot Node Termination Handler has started successfully!
2020/01/31 22:37:05 Request to instance metadata failed. Retrying.
```

hostnetwork: true
```
mrbecker@local  ~/Workspace/Github/aws-node-termination-handler   master ●  kubectl logs --namespace kube-system aws-node-termination-handler-qpmlb
2020/01/31 22:40:59 Successufully retrieved node: ip-192-168-127-207.ec2.internal
2020/01/31 22:40:59 Kubernetes Spot Node Termination Handler has started successfully!
```

**Comment by marcincuber** [comment]
@mattrandallbecker thanks for providing the solution.

However, I have an interesting observation to share. I have three EKS cluster, three different accounts and all of them are running the same setup with the same userdata which is blocking access to instance profile data.

On two EKS clusters aws-node-termination-handler works fine, only one cluster which I spinned up few days ago has the node handler failing. I haven't specified `hostnetwork: true` on any of them yet. 

Did you experience the same behaviour? Is that worth investigating in some way?

**Comment by cdaniluk** [comment]
@marcincuber you sure those nodes just didn't reboot? The way the EKS docs have you set that isn't persistent across reboots.

**Comment by cdaniluk** [comment]
@mattrandallbecker I had a feeling the control plane would break with that change. Maybe you could use two pods in the daemonset with different networking settings? They would then be able to talk internally. Perhaps a little complicated, though..

I don't see how IMDSv2 will help with this issue, though. The endpoint isn't authenticated per say, it's just session based. Any pod running on the instance could request a token from the service.

**Comment by marcincuber** [comment]
@cdaniluk I tested it with a new instance which has correct userdata, no reboot and it still works on some of my clusters.

**Comment by mattrandallbecker** [comment]
Yep, the preliminary PR that I made just to change the hostNetwork: true broke all our integration tests because it could no longer route to the in cluster service we were standing up to mock metadata.  So it stands to reason we also would have problems issuing the cordon and drain commands.

I definitely didn't fully understand the problem with my first recommendation, in fact IMDSv2 doesn't work without hostNetwork true anyways.  We'll keep digging and try to figure out a way to make it work for people using IAM Roles for Service Accounts and those who aren't.  I'll post any updates I find in this thread and will keep the readme restriction until it's resolved.

**Comment by mattrandallbecker** [comment]
Closing the loop on this thread, with our new 1.2.0 release we have the daemonset set to run on hostnetwork, the handler should now work even when following the EKS documentation starting with that version.
