### ISSUE TITLE
Create webhookTemplate configmap inside helm

### ISSUE THREAD

**Issue by NicoForce** [aws/aws-node-termination-handler#809]
**Describe the feature**
Instead of using `webhookTemplateConfigMapName` and `webhookTemplateConfigMapKey`, the helm repo should create it's own configmap by default and allow the user to set the configmap content on a helm value, e.g. `webhookTemplateConfigMapContent`.

**Is the feature request related to a problem?**
Helm currently does not allow a user to add kubernetes files to an existing chart, as such there is no way to easily add the configmap without creating it manually or depend on another chart maintained by the final user.

**Describe alternatives you've considered**

- Manually creating configmap before installing the helm chart
- Creating another helm chart and install it before the node termination handler chart
- Creating a helm chart that depends on the node termination handler chart
- Adding a hook to helmfile to install the configmap with a script

None of these are ideal solutions, which is why I'm suggesting this feature.

**Comment by NicoForce** [comment]
Commenting to remove Stale Label.

**Comment by pete911** [comment]
Hi @NicoForce, just out of interest, is there a reason no to use `webhookTemplate`. Looks like it does what you want, you can just supply the template content as value. From the code it looks like you can set one or the other - https://github.com/aws/aws-node-termination-handler/blob/main/pkg/webhook/webhook.go#L41
So my understanding is that you can use configmap if it already exists (as you mentioned, some other charts creates it), otherwise you should just use `webhookTemplate`.

**Comment by NicoForce** [comment]
Hi @pete911 , I hadn't noticed that webhookTemplate was available in the helm configuration, that should cover this use case, I'll test it out, thanks for your help!
