### ISSUE TITLE
Pods immediately evicted from Node as Spot Interruption Event is received

### ISSUE THREAD

**Issue by JulesLalu** [aws/aws-node-termination-handler#858]
We run aws-node-termination-handler (helm chart version : v0.18.5) in our EKS cluster together with Karpenter. 
The NTH does catch the Spot Interruption Events, but when it does, it immediately evicts the pods that are present on the node to be drained, and then provisions the evicted pods on other nodes.
This generates service disruption, when we could expect a smoother behavior : the pods that are on the node to be drained could be kept running until the node is actually drained (two minutes after the event was received), while other replicas of those pods are launched on another node.
Maybe this "smoother" behavior is the one intended by the node termination handler, and there is a bug in our installation ?
Would migrating to the Karpenter Interruption Handling solve this problem ?

Thanks in advance for your help !

**Comment by shapirus** [comment]
This is a good question. Is there a way to make NTH delay pod eviction for a certain (configurable) amount of time after receiving a spot interruption event in order to provide time for the deregistration of the node from the load balancer's Target Group?

Otherwise, it leads to eviction of the pods while the LB is still sending new connections to the node, which results in a service disruption.

**Comment by shapirus** [comment]
In fact, there should be not even a fixed delay, but a confirmation that the node has been deregistered from all the Target Groups.

Before it is deregistered, the Load Balancer(s) will keep routing new connections to it. When new connections are still being routed to the node, we cannot start evicting any pods, because it will mean failed connections aka service disruption.

To prevent any chance (save for the situation of the TG deregistration taking longer than the spot termination grace period) of failed connections the sequence of events must be the following:

- a Spot Termination Notification event is received
- the node is cordoned to prevent new pods being started on it
- deregstration of the node from all the Target Groups is initiated
- wait until the deregistration finishes to make sure no new connections will now come to it
- drain the node (evict all pods)

Obviously NTH cannot handle this on its own, because it doesn't work with LBs. However, setting `excludeFromLoadBalancers` to `true` will make it add a label which is used by other software to deregister the node from the TGs.

Then, NTH will need to wait until the deregistration is complete. Not sure of a good way to do it. Wait until a "deregistration finished" label is set on the node, maybe?

Any thoughts?
